FROM openjdk:21-jdk-slim AS builder
WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY settings.gradle.kts build.gradle.kts ./
RUN chmod +x gradlew

RUN ./gradlew --no-daemon help

COPY src src

RUN ./gradlew --no-daemon bootJar

FROM openjdk:21-jdk-slim
WORKDIR /app

COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 7000

ENTRYPOINT ["java","-jar","/app/app.jar"]