services:
  postgres-database:
    image: postgres:16
    container_name: postgres-video-metadata
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATASOURCE_NAME}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile-springboot
    container_name: video-metadata-service
    restart: unless-stopped
    depends_on:
      - postgres-database
    env_file:
      - .env
    ports:
      - "7000:7000"

volumes:
  postgres_data: